---
- name: Download GoLand Tarball
  become: no
  get_url:
      url: "https://download.jetbrains.com/go/goland-{{go_goland_version}}.tar.gz"
      dest: "{{ansible_user_dir}}/{{base_download_directory}}/goland-{{go_goland_version}}.tar.gz"
      mode: 0444
  when: go_goland_install

- name: Uncompress GoLand Tarball
  become: no
  unarchive:
      src: "{{ansible_user_dir}}/{{base_download_directory}}/goland-{{go_goland_version}}.tar.gz"
      dest: "{{ansible_user_dir}}/{{base_software_directory}}"
      copy: no
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0555
      creates: "{{ansible_user_dir}}/{{base_software_directory}}/GoLand-{{go_goland_version}}/build.txt"
  when: go_goland_install

- name: Create Softlink To GoLand
  become: no
  file:
      src: "{{ansible_user_dir}}/{{base_software_directory}}/GoLand-{{go_goland_version}}"
      dest: "{{ansible_user_dir}}/{{base_software_directory}}/goland"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      state: link
  when: go_goland_install

- name: Create Desktop Icon For GoLand
  become: no
  template:
      src: "templates/goland.desktop.j2"
      dest: "{{ansible_user_dir}}/Desktop/goland.desktop"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0755
  when: go_goland_install

- name: Set Global Environment To Have GoLand Use Shared JDK
  become: yes
  template:
      src: "templates/go-environment.sh.j2"
      dest: "/etc/profile.d/goland-environment.sh"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0555
  when: go_goland_install

- name: Remove GoLand's Embedded JDK
  become: no
  file:
      path: "{{ansible_user_dir}}/{{base_software_directory}}/goland/jre"
      state: absent
  when: go_goland_install
